# pyproject.toml

# --- [tool.black] ---
# Code formatter:
[tool.black]
line-length = 88
target-version = ['py312', 'py313']
include = '\.pyi?$'

# --- [tool.ruff] ---
# Code linter:
[tool.ruff]
# E = pycodestyle, F = pyflakes, B = bugbear
select = ["E", "F", "W", "I", "B"]
ignore = [
    "E501",
]
line-length = 88

# Ruff's built-in formatter section
[tool.ruff.format]
