# pyproject.toml

# --- [tool.ruff] ---
# Code linter:
[tool.ruff]
# E = pycodestyle, F = pyflakes, B = bugbear
select = ["E", "F", "W", "I", "B"]
ignore = [
    "E501",
]
line-length = 88

# Ruff's built-in formatter section
[tool.ruff.format]
